---
development:
  cloud_name: drhsmvjve
  api_key: '853618565518277'
  api_secret: RpCRK0as_DNhSPRbIKJLcCzMRjg
  enhance_image_tag: true
  static_image_support: false
production:
  cloud_name: drhsmvjve
  api_key: '853618565518277'
  api_secret: RpCRK0as_DNhSPRbIKJLcCzMRjg
  enhance_image_tag: true
  static_image_support: true
test:
  cloud_name: drhsmvjve
  api_key: '853618565518277'
  api_secret: RpCRK0as_DNhSPRbIKJLcCzMRjg
  enhance_image_tag: true
  static_image_support: false
